version: '3'

services:
  livri-dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    ports:
      - "8000:8000"
    volumes:
      - livri-dynamodb-data:/home/dynamodblocal
    networks:
      - livri-network

volumes:
  livri-dynamodb-data:

networks: 
  livri-network:
    driver: bridge