version: '3'

services:
  livri-dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    ports:
      - "8000:8000"
    volumes:
      - livri-dynamodb-data:/home/dynamodblocal
    networks:
      - livri-network

  # livri-postgres:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: "password"
  #   ports:
  #     - "5432:5432"
  #   # volumes:
  #   #   - livri-postgres-data:/var/lib/postgresql/data 
  #   networks:
  #     - livri-network

volumes:
  livri-dynamodb-data:

networks: 
  livri-network:
    driver: bridge